version: "3.1"
services:
  ldap:
    container_name: apacheds
    build: ./build
    ports:
      - "10389:10389"
    # Note: Uncomment this if you have ldif files you want to bootstrap
    #environment:
    #  - BOOTSTRAP_FILE=/bootstrap/the-file.ldif
    volumes:
      - apacheds_data:/var/lib/apacheds-2.0.0_M24/default
      - ./bootstrap:/bootstrap
    secrets:
      - apacheds_admin_password
    # uncomment if you need to use a network to connect this LDAP server with another container
    #networks:
    #  - apacheds
volumes:
  apacheds_data:
    external: true
secrets:
  apacheds_admin_password:
    file: ./apacheds_admin_password.secret
# uncommend if you need to use a network to connect this LDAP server with another container
#networks:
#  apacheds:
#    external: true