version: "3.1"
services:
  ldap:
    container_name: apacheds
    build: ./build
    ports:
      - "10389:10389"
    # Note: Uncomment this if you have ldif files you want to bootstrap
    #environment:
    #  - BOOTSTRAP_FILE=/bootstrap/the-file.ldif
    volumes:
      - apacheds_data:/var/lib/apacheds-2.0.0_M24/default
      - ./bootstrap:/bootstrap
    secrets:
      - apacheds_admin_password
    networks:
      - harbor
volumes:
  apacheds_data:
    external: true
secrets:
  apacheds_admin_password:
    file: ./apacheds_admin_password.secret
networks:
  harbor:
    external: true