version: "3.1"
services:
  ldap:
    build: ./build
    ports:
      - "10389:10389"
    # Note: Uncomment this if you have ldif files you want to bootstrap
    #environment:
    #  - BOOTSTRAP_FILE=/bootstrap/the-file.ldif
    volumes:
      - "apacheds_data:/data/"
      - "./bootstrap:/bootstrap/"
    secrets:
      - apacheds_admin_password
volumes:
  apacheds_data:
secrets:
  apacheds_admin_password:
    file: ./apacheds_admin_password.secret